{
  "comments": [
    {
      "key": {
        "uuid": "f2c51ada_26828d54",
        "filename": "api-lib/vnc_api/vnc_api.py",
        "patchSetId": 1
      },
      "lineNbr": 535,
      "author": {
        "id": 782
      },
      "writtenOn": "2019-09-27T23:57:18Z",
      "side": 1,
      "message": "if not timeout:\n  timeout \u003d _read_cfg(cfg_parser, \u0027global\u0027, \u0027TIMEOUT\u0027, self._DEFAULT_TIMEOUT))\nself._timeout \u003d int(timeout)",
      "revId": "6e45e21a4aab0f59387006337a77892eca676d3e",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}